import type { AcademicLesson, LessonData } from '../src/app/types'

const lessons: Record<string, LessonData> = {
  'lesson-free-fall': {
    course: 'mechanics', kicker: 'Mecânica · Movimento variado', title: 'Queda livre',
    lead: 'Como um corpo cai quando a única força relevante é a gravidade.',
    concept: 'Em queda livre ideal, desprezamos a resistência do ar. Perto da superfície da Terra, a aceleração é aproximadamente constante e aponta para baixo. Isso significa que a velocidade muda na mesma proporção a cada segundo.',
    callout: 'O objeto não “ganha uma velocidade fixa”; ele ganha aproximadamente 9,8 m/s de velocidade vertical a cada segundo.',
    formulas: [['a = g', 'aceleração constante'], ['v = v₀ + gt', 'velocidade após o tempo t'], ['y = y₀ + v₀t + ½gt²', 'posição vertical, adotando para baixo como positivo']],
    deduction: 'Partimos da definição de aceleração constante, a = Δv/Δt. Reorganizando, Δv = at. Se no instante inicial a velocidade é v₀, então v − v₀ = at e v = v₀ + at. Para a posição, a velocidade média no intervalo é (v₀ + v)/2; multiplicando pelo tempo e substituindo v, obtemos Δy = v₀t + ½at².',
    question: 'Um objeto é abandonado de uma altura de 19,6 m. Usando g = 9,8 m/s², em quanto tempo ele atinge o solo?',
    options: ['1 s', '2 s', '4 s'], answer: 1,
    explanation: 'Como h = ½gt², temos 19,6 = 4,9t². Logo, t² = 4 e t = 2 s.', visual: 'free-fall',
  },
  'lesson-ohm': {
    course: 'electricity', kicker: 'Eletricidade · Circuitos', title: 'Lei de Ohm',
    lead: 'A relação entre a diferença de potencial aplicada, a corrente e a resistência de um componente.',
    concept: 'Em um resistor ôhmico, mantendo as condições físicas constantes, a corrente é proporcional à tensão aplicada. A resistência mede o quanto o componente se opõe ao movimento ordenado de cargas.',
    callout: 'A lei de Ohm é um modelo para determinados materiais e faixas de operação; ela não é uma propriedade universal de todo componente elétrico.',
    formulas: [['U = Ri', 'lei de Ohm'], ['i = U/R', 'corrente em um resistor'], ['P = Ui = Ri² = U²/R', 'potência dissipada']],
    deduction: 'No gráfico U em função de i para um resistor ôhmico, a relação é uma reta que passa pela origem. O coeficiente angular dessa reta é R: R = ΔU/Δi. Assim, dobrar a tensão dobra a corrente quando a resistência permanece constante.',
    question: 'Um resistor de 12 Ω é ligado a uma fonte de 24 V. Qual é a corrente no resistor?',
    options: ['0,5 A', '2 A', '12 A'], answer: 1,
    explanation: 'Aplicando i = U/R, temos i = 24/12 = 2 A.', visual: 'circuit',
  },
  'lesson-wave-speed': {
    course: 'waves', kicker: 'Ondas · Grandezas periódicas', title: 'Velocidade da onda',
    lead: 'Como comprimento de onda e frequência determinam a rapidez de repetição de um padrão.',
    concept: 'Uma onda transporta energia e informação por meio de uma perturbação. O comprimento de onda λ é a distância entre pontos equivalentes consecutivos; a frequência f indica quantos ciclos passam por um ponto a cada segundo.',
    callout: 'A velocidade de propagação depende do meio. Ao mudar de meio, a frequência é mantida pela fonte, enquanto λ se ajusta para que v = λf continue válido.',
    formulas: [['T = 1/f', 'período de um ciclo'], ['v = λf', 'velocidade de propagação'], ['v = λ/T', 'mesma relação escrita com o período']],
    deduction: 'Em um período T, uma crista avança exatamente um comprimento de onda λ. Logo, velocidade é distância dividida pelo tempo: v = λ/T. Como 1/T = f, segue v = λf.',
    question: 'Uma onda tem λ = 0,80 m e frequência 12,5 Hz. Qual é sua velocidade?',
    options: ['10 m/s', '12,5 m/s', '15,6 m/s'], answer: 0,
    explanation: 'Usando v = λf, temos v = 0,80 × 12,5 = 10 m/s.', visual: 'waves',
  },
  'lesson-heat': {
    course: 'thermo', kicker: 'Termologia · Energia térmica', title: 'Calor sensível',
    lead: 'Como a energia transferida altera a temperatura de um corpo sem mudar seu estado físico.',
    concept: 'Calor é energia transferida por diferença de temperatura. Quando essa energia modifica a agitação microscópica sem produzir mudança de fase, chamamos o efeito de calor sensível.',
    callout: 'Temperatura não é a mesma coisa que calor: temperatura caracteriza o estado térmico; calor é energia em trânsito.',
    formulas: [['Q = mcΔT', 'calor sensível'], ['c = Q/(mΔT)', 'calor específico'], ['ΔT = T_f − T_i', 'variação de temperatura']],
    deduction: 'A capacidade térmica C de um corpo é a energia necessária para elevar sua temperatura em uma unidade: Q = CΔT. Como C é proporcional à massa, C = mc, então Q = mcΔT. O calor específico c depende do material.',
    question: 'Um bloco de 2 kg, com c = 500 J/(kg·°C), recebe 10.000 J. Qual é a variação de temperatura?',
    options: ['5 °C', '10 °C', '20 °C'], answer: 1,
    explanation: 'ΔT = Q/(mc) = 10.000/(2 × 500) = 10 °C.', visual: 'thermo',
  },
  'lesson-units': { course: 'mechanics', kicker: 'Mecânica · Linguagem da Física', title: 'Grandezas e unidades', lead: 'Como comunicar medidas de modo comparável e consistente.', concept: 'Grandezas físicas são propriedades mensuráveis, como comprimento, massa e tempo. O Sistema Internacional define unidades de referência para que uma medida tenha o mesmo significado em qualquer lugar.', callout: 'Sempre converta as grandezas para unidades compatíveis antes de substituir valores em uma fórmula.', formulas: [['1 km = 1.000 m', 'conversão de comprimento'], ['v = Δs/Δt', 'unidades de velocidade: m/s']], deduction: 'Uma unidade não é um enfeite do número: ela informa qual grandeza foi medida. Nas conversões, multiplicamos por fatores equivalentes a 1 para trocar a unidade sem mudar o valor físico.', question: 'Quantos metros correspondem a 2,5 km?', options: ['25 m', '250 m', '2.500 m'], answer: 2, explanation: 'Como 1 km equivale a 1.000 m, 2,5 km equivalem a 2.500 m.', visual: 'projectile' },
  'lesson-graphs': { course: 'mechanics', kicker: 'Mecânica · Linguagem da Física', title: 'Leitura de gráficos', lead: 'Como extrair informação física da relação entre duas grandezas.', concept: 'Um gráfico mostra como uma variável depende de outra. Em um gráfico posição × tempo, a inclinação indica velocidade; em velocidade × tempo, a área sob a curva indica deslocamento.', callout: 'Leia os eixos e suas unidades antes de interpretar inclinações, áreas ou pontos do gráfico.', formulas: [['v = Δs/Δt', 'inclinação em s × t'], ['Δs = área sob v × t', 'deslocamento']], deduction: 'A inclinação é a razão entre a variação vertical e a horizontal. Como velocidade é variação de posição por tempo, ela é a inclinação no gráfico s × t.', question: 'Qual grandeza é dada pela área sob um gráfico velocidade × tempo?', options: ['Aceleração', 'Deslocamento', 'Força'], answer: 1, explanation: 'Velocidade multiplicada pelo intervalo de tempo produz deslocamento.', visual: 'projectile' },
  'lesson-uniform': { course: 'mechanics', kicker: 'Mecânica · Movimento', title: 'Movimento uniforme', lead: 'O movimento em que a velocidade permanece constante.', concept: 'No movimento uniforme, o corpo percorre deslocamentos iguais em intervalos de tempo iguais. Não há aceleração e a posição varia linearmente com o tempo.', callout: 'Velocidade constante não significa posição constante: o corpo continua mudando de lugar.', formulas: [['Δs = vt', 'deslocamento'], ['s = s₀ + vt', 'posição']], deduction: 'Se a velocidade é constante, a razão Δs/Δt mantém o mesmo valor. Multiplicando pelos intervalos de tempo, obtemos Δs = vt.', question: 'Um ciclista mantém 6 m/s por 30 s. Qual deslocamento realiza?', options: ['36 m', '180 m', '900 m'], answer: 1, explanation: 'Δs = vt = 6 × 30 = 180 m.', visual: 'projectile' },
  'lesson-varied': { course: 'mechanics', kicker: 'Mecânica · Movimento', title: 'Movimento variado', lead: 'Como descrever movimentos em que a velocidade muda.', concept: 'Quando a velocidade muda em módulo, direção ou sentido, existe aceleração. Em aceleração constante, a variação de velocidade é proporcional ao tempo.', callout: 'A aceleração pode ser negativa; isso depende do eixo escolhido e não significa automaticamente que o corpo está diminuindo a rapidez.', formulas: [['a = Δv/Δt', 'aceleração média'], ['v = v₀ + at', 'velocidade com aceleração constante']], deduction: 'A definição de aceleração é a taxa de variação da velocidade. Se essa taxa é constante, Δv = at e v = v₀ + at.', question: 'A velocidade passa de 4 m/s para 16 m/s em 3 s. Qual aceleração média?', options: ['4 m/s²', '12 m/s²', '20 m/s²'], answer: 0, explanation: 'a = (16 − 4)/3 = 4 m/s².', visual: 'projectile' },
  'lesson-newton': { course: 'mechanics', kicker: 'Mecânica · Forças', title: 'As leis de Newton', lead: 'Como as forças explicam repouso, movimento e aceleração.', concept: 'A primeira lei descreve a inércia; a segunda relaciona força resultante e aceleração; a terceira estabelece que forças surgem em pares em corpos diferentes.', callout: 'A força resultante, e não uma força isolada, é o que determina a aceleração do corpo.', formulas: [['ΣF = ma', 'segunda lei de Newton'], ['P = mg', 'peso próximo à Terra']], deduction: 'Ao escolher um corpo e um eixo, somamos as forças na direção desse eixo. A força resultante é igual ao produto da massa pela aceleração.', question: 'Uma pessoa de 60 kg acelera para cima a 2 m/s², com g = 10 m/s². Qual é a normal?', options: ['480 N', '600 N', '720 N'], answer: 2, explanation: 'N − mg = ma; assim N = 60(10 + 2) = 720 N.', visual: 'projectile' },
  'lesson-circular': { course: 'mechanics', kicker: 'Mecânica · Forças', title: 'Movimento circular', lead: 'Por que mudar continuamente de direção exige aceleração.', concept: 'Mesmo com rapidez constante, um corpo em trajetória circular muda de direção. Essa mudança produz aceleração centrípeta, apontada para o centro da curva.', callout: 'Força centrípeta não é uma nova força: é o nome da resultante dirigida ao centro.', formulas: [['a_c = v²/R', 'aceleração centrípeta'], ['F_c = mv²/R', 'força resultante radial']], deduction: 'Em uma volta, o vetor velocidade muda de direção. Quanto maior a rapidez ou menor o raio, maior deve ser essa variação por tempo e, portanto, a aceleração.', question: 'Se a velocidade dobra em uma curva de mesmo raio, como muda a aceleração centrípeta?', options: ['Dobra', 'Quadruplica', 'Cai pela metade'], answer: 1, explanation: 'Como a_c depende de v², dobrar v multiplica a aceleração por 4.', visual: 'projectile' },
  'lesson-circuits': { course: 'electricity', kicker: 'Eletricidade · Circuitos', title: 'Circuitos em série', lead: 'Como corrente, tensão e resistência se comportam em uma única trajetória.', concept: 'Em uma associação em série, a mesma corrente atravessa todos os componentes. A resistência equivalente é a soma das resistências, e a tensão da fonte se divide entre elas.', callout: 'Somar resistências diretamente vale para série; em paralelo, a relação é diferente.', formulas: [['R_eq = R₁ + R₂ + …', 'resistência em série'], ['U = U₁ + U₂ + …', 'tensões no circuito']], deduction: 'Como não há bifurcação, a carga que passa por um componente passa pelos demais. Somando as quedas de potencial e aplicando Ohm, obtemos a resistência equivalente.', question: 'Resistores de 2 Ω e 4 Ω em série ligados a 12 V conduzem qual corrente?', options: ['0,5 A', '2 A', '6 A'], answer: 1, explanation: 'R_eq = 6 Ω e i = U/R_eq = 12/6 = 2 A.', visual: 'circuit' },
  'lesson-power': { course: 'electricity', kicker: 'Eletricidade · Energia elétrica', title: 'Potência elétrica', lead: 'A rapidez com que a energia elétrica é transferida ou transformada.', concept: 'Potência elétrica mede energia por unidade de tempo. Em aparelhos resistivos, ela pode aparecer como aquecimento, luz ou movimento.', callout: 'Potência é medida em watt; consumo de energia é potência multiplicada pelo tempo.', formulas: [['P = Ui', 'potência elétrica'], ['E = Pt', 'energia transferida']], deduction: 'Tensão é energia por carga e corrente é carga por tempo. Multiplicando U por i, obtemos energia por tempo: potência.', question: 'Um aparelho opera com 120 V e 2 A. Qual é sua potência?', options: ['60 W', '120 W', '240 W'], answer: 2, explanation: 'P = Ui = 120 × 2 = 240 W.', visual: 'circuit' },
  'lesson-interference': { course: 'waves', kicker: 'Ondas · Ondas', title: 'Interferência', lead: 'O que acontece quando duas perturbações ocupam a mesma região.', concept: 'Pelo princípio da superposição, o deslocamento resultante é a soma algébrica dos deslocamentos das ondas. Ondas em fase reforçam-se; em oposição de fase podem cancelar-se.', callout: 'Interferência não destrói necessariamente as ondas: após se cruzarem, elas continuam sua propagação.', formulas: [['y_R = y₁ + y₂', 'superposição'], ['Δφ = 0', 'reforço em fase']], deduction: 'Em um meio linear, cada onda produz seu deslocamento independentemente. No ponto de encontro, os deslocamentos são somados instante a instante.', question: 'Duas ondas idênticas chegam em fase a um ponto. O que ocorre?', options: ['Interferência construtiva', 'Interferência destrutiva', 'Nenhuma alteração'], answer: 0, explanation: 'Crestas e vales coincidem, aumentando a amplitude resultante.', visual: 'waves' },
  'lesson-phase': { course: 'thermo', kicker: 'Termologia · Calor e temperatura', title: 'Mudanças de fase', lead: 'Como a energia pode alterar o estado físico sem variar a temperatura.', concept: 'Durante uma mudança de fase de uma substância pura sob pressão constante, a energia trocada reorganiza as interações microscópicas. A temperatura se mantém constante até a transição terminar.', callout: 'Use calor latente durante a mudança de fase; use calor sensível apenas quando a temperatura varia.', formulas: [['Q = mL', 'calor latente'], ['Q = mcΔT', 'calor sensível']], deduction: 'A energia necessária para mudar o estado físico é proporcional à massa. A constante de proporcionalidade L é o calor latente do material.', question: 'Na fusão de uma substância pura à pressão constante, a temperatura:', options: ['Aumenta', 'Permanece constante', 'Diminui'], answer: 1, explanation: 'A energia recebida é usada na mudança de fase, não no aumento de temperatura.', visual: 'thermo' },
}

export const academicLessons: Record<string, AcademicLesson> = {
  'lesson-free-fall': {
    definitions: [['Queda livre', 'movimento em que a força gravitacional é a única força relevante.'], ['Aceleração gravitacional', 'aceleração aproximadamente constante, orientada para o centro da Terra.'], ['Referencial', 'sistema escolhido para medir posições, velocidades e tempos.']],
    interpretation: 'O sinal de g depende do eixo escolhido. Escolher “para baixo positivo” torna g positivo; escolher “para cima positivo” torna g negativo. A física é a mesma desde que todas as grandezas respeitem a convenção.',
    example: 'Uma bola lançada para cima com v₀ = 15 m/s, usando g = 10 m/s², atinge o ponto mais alto quando v = 0. Pela equação v = v₀ − gt, t = 1,5 s. Nesse instante, Δy = 15·1,5 − 5·(1,5)² = 11,25 m.',
    pitfalls: 'Confundir velocidade nula no ponto mais alto com aceleração nula; usar g = 0 porque o corpo “parou” momentaneamente; ignorar a escolha do eixo e misturar sinais.',
  },
  'lesson-ohm': {
    definitions: [['Diferença de potencial', 'energia transferida por unidade de carga entre dois pontos.'], ['Corrente elétrica', 'taxa de passagem ordenada de carga por uma seção.'], ['Resistência', 'razão U/i em um resistor ôhmico.']],
    interpretation: 'No diagrama U × i, a inclinação representa a resistência. Em uma associação em paralelo, a tensão é a mesma nos ramos; em série, a corrente é a mesma nos componentes.',
    example: 'Dois resistores de 6 Ω e 3 Ω em paralelo têm resistência equivalente dada por 1/R = 1/6 + 1/3, portanto R = 2 Ω. Ligados a 12 V, a corrente total é 6 A.',
    pitfalls: 'Somar resistores em paralelo como se estivessem em série; confundir potência com energia; assumir que todo componente obedece à lei de Ohm em qualquer condição.',
  },
  'lesson-wave-speed': {
    definitions: [['Comprimento de onda', 'distância entre pontos equivalentes consecutivos.'], ['Frequência', 'número de oscilações por unidade de tempo.'], ['Superposição', 'princípio segundo o qual perturbações se somam quando ocupam a mesma região.']],
    interpretation: 'Quando a fonte mantém a frequência e a onda entra em outro meio, sua velocidade e seu comprimento podem mudar. O período, porém, permanece ligado à fonte.',
    example: 'Se uma onda passa de um meio onde v = 20 m/s para outro onde v = 12 m/s, mantendo f = 5 Hz, o comprimento de onda passa de 4 m para 2,4 m.',
    pitfalls: 'Achar que a frequência sempre muda ao trocar de meio; confundir amplitude com comprimento de onda; usar λ = v/f invertido.',
  },
  'lesson-heat': {
    definitions: [['Calor', 'energia transferida devido a uma diferença de temperatura.'], ['Calor específico', 'energia necessária para elevar em um grau a temperatura de uma unidade de massa.'], ['Equilíbrio térmico', 'estado em que não há transferência líquida de calor entre corpos em contato.']],
    interpretation: 'A mesma quantidade de calor pode produzir variações de temperatura diferentes, pois massa e material importam. Durante uma mudança de fase ideal, o calor altera a organização microscópica, não a temperatura.',
    example: 'Para aquecer 2 kg de um material com c = 500 J/(kg·°C) em 8 °C, Q = 2·500·8 = 8000 J.',
    pitfalls: 'Tratar calor como propriedade armazenada; esquecer que ΔT é uma diferença; usar calor sensível durante uma mudança de fase.',
  },
  'lesson-units': { definitions: [['Grandeza', 'propriedade que pode ser medida.'], ['Unidade', 'padrão de comparação de uma grandeza.'], ['SI', 'Sistema Internacional de Unidades.']], interpretation: 'Uma medida só é completa quando contém número e unidade.', example: '2,5 km correspondem a 2.500 m.', pitfalls: 'Misturar unidades incompatíveis em uma mesma conta.' },
  'lesson-graphs': { definitions: [['Eixo', 'linha que representa uma variável.'], ['Inclinação', 'variação vertical por variação horizontal.'], ['Área', 'região sob uma curva.']], interpretation: 'A interpretação depende de quais grandezas ocupam os eixos.', example: 'Em v × t, a área representa deslocamento.', pitfalls: 'Ignorar escala e unidade dos eixos.' },
  'lesson-uniform': { definitions: [['Velocidade', 'deslocamento por tempo.'], ['Movimento uniforme', 'movimento com velocidade constante.'], ['Posição', 'localização no referencial.']], interpretation: 'O gráfico posição × tempo é uma reta.', example: 'A 6 m/s por 30 s, Δs = 180 m.', pitfalls: 'Confundir velocidade constante com repouso.' },
  'lesson-varied': { definitions: [['Aceleração', 'variação da velocidade por tempo.'], ['Velocidade inicial', 'velocidade no instante de referência.'], ['Referencial', 'sistema usado para descrever o movimento.']], interpretation: 'O sinal depende da orientação do eixo escolhida.', example: 'De 4 para 16 m/s em 3 s, a = 4 m/s².', pitfalls: 'Confundir aceleração negativa com velocidade negativa.' },
  'lesson-newton': { definitions: [['Inércia', 'tendência de manter o estado de movimento.'], ['Força resultante', 'soma vetorial das forças.'], ['Massa', 'medida de inércia.']], interpretation: 'Os pares de ação e reação atuam em corpos diferentes.', example: 'No elevador, N − mg = ma.', pitfalls: 'Cancelar ação e reação no diagrama de um único corpo.' },
  'lesson-circular': { definitions: [['Raio', 'distância até o centro da trajetória.'], ['Centrípeta', 'direção apontada ao centro.'], ['Rapidez', 'módulo da velocidade.']], interpretation: 'A velocidade tangencia a trajetória, enquanto a aceleração aponta ao centro.', example: 'Dobrar a rapidez quadruplica a aceleração centrípeta.', pitfalls: 'Tratar a força centrípeta como força adicional.' },
  'lesson-circuits': { definitions: [['Série', 'uma única trajetória de corrente.'], ['Corrente', 'mesma em todos os componentes.'], ['Resistência equivalente', 'resistência total do conjunto.']], interpretation: 'A tensão é dividida entre os resistores em série.', example: '2 Ω + 4 Ω resultam em 6 Ω.', pitfalls: 'Aplicar a regra de soma direta a resistores em paralelo.' },
  'lesson-power': { definitions: [['Potência', 'energia transferida por tempo.'], ['Watt', 'joule por segundo.'], ['Energia elétrica', 'potência acumulada ao longo do tempo.']], interpretation: 'Dois aparelhos podem ter mesma energia consumida em tempos diferentes.', example: '120 V e 2 A correspondem a 240 W.', pitfalls: 'Confundir watt com watt-hora.' },
  'lesson-interference': { definitions: [['Superposição', 'soma dos deslocamentos.'], ['Fase', 'posição no ciclo de oscilação.'], ['Amplitude', 'máximo deslocamento.']], interpretation: 'A interferência depende da diferença de fase no encontro.', example: 'Duas ondas em fase produzem reforço.', pitfalls: 'Achar que uma onda deixa de existir após o cruzamento.' },
  'lesson-phase': { definitions: [['Fusão', 'passagem de sólido para líquido.'], ['Calor latente', 'energia por massa em mudança de fase.'], ['Equilíbrio térmico', 'ausência de fluxo líquido de calor.']], interpretation: 'A temperatura fica constante durante a transição de uma substância pura.', example: 'Na fusão, Q = mL.', pitfalls: 'Usar Q = mcΔT enquanto a temperatura está constante.' },
}

export const lessonDataById: Record<string, LessonData> = lessons

export function academicLessonById(id: string) { return academicLessons[id] }
