import type { Question } from '../src/app/types'

export const questionBank: Question[] = [
  { id: 'q-units', lessonId: 'lesson-units', topic: 'Grandezas e unidades', course: 'mechanics', difficulty: 'easy', objective: 'Unidades', format: 'Conversão', prompt: 'Quantos metros correspondem a 2,5 km?', options: ['25 m', '250 m', '2.500 m'], answer: 2, reasoning: 'Usar o prefixo quilo = mil.', explanation: '2,5 km = 2,5 × 1.000 m = 2.500 m.' },
  { id: 'q-graphs', lessonId: 'lesson-graphs', topic: 'Leitura de gráficos', course: 'mechanics', difficulty: 'medium', objective: 'Interpretação', format: 'Gráfico v × t', prompt: 'Um trem acelera de 0 a 20 m/s em 10 s e mantém essa velocidade por 15 s. Qual distância percorre?', options: ['250 m', '400 m', '500 m'], answer: 1, reasoning: 'A distância é a área sob o gráfico v × t.', explanation: 'Triângulo: 100 m; retângulo: 300 m. Total: 400 m.' },
  { id: 'q-uniform', lessonId: 'lesson-uniform', topic: 'Movimento uniforme', course: 'mechanics', difficulty: 'easy', objective: 'Cálculo', format: 'Aplicação direta', prompt: 'Um ciclista mantém 6 m/s por 30 s. Qual deslocamento realiza?', options: ['36 m', '180 m', '900 m'], answer: 1, reasoning: 'Aplicar Δs = vt.', explanation: 'Δs = 6 × 30 = 180 m.' },
  { id: 'q-varied', lessonId: 'lesson-varied', topic: 'Movimento variado', course: 'mechanics', difficulty: 'medium', objective: 'Cálculo', format: 'Aceleração', prompt: 'A velocidade de um carro passa de 4 m/s para 16 m/s em 3 s. Qual é a aceleração média?', options: ['4 m/s²', '12 m/s²', '20 m/s²'], answer: 0, reasoning: 'Usar a = Δv/Δt.', explanation: 'a = (16 − 4)/3 = 4 m/s².' },
  { id: 'q-free-fall', lessonId: 'lesson-free-fall', topic: 'Queda livre', course: 'mechanics', difficulty: 'medium', objective: 'Modelagem', format: 'Queda vertical', prompt: 'Um objeto é abandonado de 19,6 m, com g = 9,8 m/s². Em quanto tempo atinge o solo?', options: ['1 s', '2 s', '4 s'], answer: 1, reasoning: 'Para queda a partir do repouso, h = ½gt².', explanation: '19,6 = 4,9t²; portanto t² = 4 e t = 2 s.' },
  { id: 'q-newton', lessonId: 'lesson-newton', topic: 'Leis de Newton', course: 'mechanics', difficulty: 'hard', objective: 'Modelagem', format: 'Situação física', prompt: 'Uma pessoa de 60 kg está em um elevador que acelera para cima a 2 m/s². Com g = 10 m/s², qual é a força normal?', options: ['480 N', '600 N', '720 N'], answer: 2, reasoning: 'Aplicar a segunda lei de Newton: N − mg = ma.', explanation: 'N = m(g + a) = 60(10 + 2) = 720 N.' },
  { id: 'q-circular', lessonId: 'lesson-circular', topic: 'Movimento circular', course: 'mechanics', difficulty: 'hard', objective: 'Comparação', format: 'Raciocínio', prompt: 'Dois carros fazem uma curva de mesmo raio. B tem o dobro da velocidade de A. Como se comparam as acelerações centrípetas?', options: ['aB = 2aA', 'aB = 4aA', 'aB = aA/2'], answer: 1, reasoning: 'a_c = v²/R.', explanation: 'Dobrar v quadruplica v²; logo aB = 4aA.' },
  { id: 'q-ohm', lessonId: 'lesson-ohm', topic: 'Lei de Ohm', course: 'electricity', difficulty: 'easy', objective: 'Circuitos', format: 'Aplicação direta', prompt: 'Um resistor de 12 Ω está ligado a 24 V. Qual é a corrente?', options: ['0,5 A', '2 A', '12 A'], answer: 1, reasoning: 'Usar i = U/R.', explanation: 'i = 24/12 = 2 A.' },
  { id: 'q-circuits', lessonId: 'lesson-circuits', topic: 'Circuitos em série', course: 'electricity', difficulty: 'medium', objective: 'Circuitos', format: 'Associação', prompt: 'Resistores de 2 Ω e 4 Ω em série são ligados a 12 V. Qual é a corrente?', options: ['0,5 A', '2 A', '6 A'], answer: 1, reasoning: 'Em série, Req = 2 + 4.', explanation: 'Req = 6 Ω e i = 12/6 = 2 A.' },
  { id: 'q-power', lessonId: 'lesson-power', topic: 'Potência elétrica', course: 'electricity', difficulty: 'medium', objective: 'Energia', format: 'Aplicação direta', prompt: 'Um aparelho opera com 120 V e 2 A. Qual é sua potência?', options: ['60 W', '120 W', '240 W'], answer: 2, reasoning: 'Usar P = Ui.', explanation: 'P = 120 × 2 = 240 W.' },
  { id: 'q-wave-speed', lessonId: 'lesson-wave-speed', topic: 'Velocidade da onda', course: 'waves', difficulty: 'medium', objective: 'Modelagem', format: 'Cálculo', prompt: 'Uma onda tem λ = 0,80 m e f = 12,5 Hz. Qual velocidade?', options: ['10 m/s', '12,5 m/s', '15,6 m/s'], answer: 0, reasoning: 'Usar v = λf.', explanation: 'v = 0,80 × 12,5 = 10 m/s.' },
  { id: 'q-interference', lessonId: 'lesson-interference', topic: 'Interferência de ondas', course: 'waves', difficulty: 'medium', objective: 'Conceito', format: 'Superposição', prompt: 'Duas ondas idênticas chegam em fase a um ponto. O que ocorre?', options: ['Interferência construtiva', 'Interferência destrutiva', 'Nenhuma alteração'], answer: 0, reasoning: 'Em fase, os deslocamentos se somam.', explanation: 'Crestas e vales coincidem, aumentando a amplitude resultante.' },
  { id: 'q-heat', lessonId: 'lesson-heat', topic: 'Calor sensível', course: 'thermo', difficulty: 'medium', objective: 'Cálculo', format: 'Calorimetria', prompt: 'Um bloco de 2 kg, c = 500 J/(kg·°C), recebe 10.000 J. Qual ΔT?', options: ['5 °C', '10 °C', '20 °C'], answer: 1, reasoning: 'Isolar ΔT em Q = mcΔT.', explanation: 'ΔT = 10.000/(2 × 500) = 10 °C.' },
  { id: 'q-phase', lessonId: 'lesson-phase', topic: 'Mudanças de fase', course: 'thermo', difficulty: 'easy', objective: 'Conceito', format: 'Estado físico', prompt: 'Durante a fusão de uma substância pura à pressão constante, a temperatura:', options: ['aumenta continuamente', 'permanece constante', 'diminui continuamente'], answer: 1, reasoning: 'O calor latente altera a organização microscópica.', explanation: 'A energia recebida é usada na mudança de fase, sem elevar a temperatura.' },
]

export function questionById(id: string) { return questionBank.find((question) => question.id === id) }
