import { useState } from 'react'
import type { AcademicLesson as AcademicLessonData, LessonData, Question, StoredResponse } from '../../app/types'
import { QuestionCard } from '../questions/QuestionCard'

export function AcademicLesson({ lesson, academic, completed, response, exercise, onAnswer, onComplete, onBack, onNavigateLesson }: { lesson: LessonData; academic?: AcademicLessonData; completed: boolean; response?: StoredResponse; exercise: Question; onAnswer: (question: Question, selected: number) => void; onComplete: () => void; onBack: () => void; onNavigateLesson: () => void }) {
  const [details, setDetails] = useState(false)
  if (!academic) return <section className="screen active"><div className="empty"><strong>Aula indisponível.</strong>O conteúdo desta aula não foi encontrado.</div><button className="btn" onClick={onBack}>Voltar à trilha</button></section>
  return <div className="lesson-layout"><aside className="lesson-aside"><button className="link-button" onClick={onBack}>← Voltar à trilha</button><div className="lesson-meter"><p>{completed ? 'Aula concluída' : 'Em andamento'}</p></div></aside><article className="lesson-main"><div className="lesson-kicker">{lesson.kicker}</div><h1>{lesson.title}</h1><p className="lesson-lead">{lesson.lead}</p><section className="academic-section"><h2>Conceito central</h2><div className="prose"><p>{lesson.concept}</p></div><div className="callout">{lesson.callout}</div></section><section className="academic-section"><h2>Conceitos-chave</h2><div className="definition-grid">{academic.definitions.map(([term, description]) => <div className="definition-item" key={term}><strong>{term}</strong><p>{description}</p></div>)}</div></section><section className="academic-section"><h2>Fórmulas</h2><div className="formula-list">{lesson.formulas.map(([formula, label]) => <div className="formula-row" key={formula}><code>{formula}</code><span>{label}</span></div>)}</div></section><section className="academic-section"><h2>Como interpretar</h2><div className="prose"><p>{academic.interpretation}</p></div><button className="reveal" onClick={() => setDetails(!details)}>{details ? 'Ocultar dedução' : 'Ver dedução'}</button>{details && <div className="reveal-panel show"><p>{lesson.deduction}</p></div>}</section><section className="academic-section"><h2>Exemplo</h2><div className="example-box"><p>{academic.example}</p></div><div className="error-box"><div className="example-label">Atenção</div><p>{academic.pitfalls}</p></div></section><section className="academic-section lesson-exercise"><div className="lesson-block-head"><h2>Exercício do tópico</h2></div><QuestionCard question={exercise} response={response} onAnswer={onAnswer} /></section><footer className="lesson-footer"><button className="btn ghost" onClick={onNavigateLesson}>Ver fichas de questões</button><button className="btn primary" onClick={onComplete}>{completed ? 'Aula concluída ✓' : 'Concluir aula'}</button></footer></article></div>
}
