alter table public.profiles
  add column if not exists timezone text not null default 'UTC';

revoke insert, delete, update on table public.profiles from authenticated;
grant update (full_name, avatar_url) on table public.profiles to authenticated;

create table if not exists public.user_daily_activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_date date not null,
  exercises_completed integer not null default 0 check (exercises_completed >= 0),
  completed_exercise_ids text[] not null default '{}',
  streak_day_completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, activity_date)
);

alter table public.user_daily_activity enable row level security;

revoke all on table public.user_daily_activity from anon, authenticated;
grant select on table public.user_daily_activity to authenticated;

drop policy if exists "Users can view their own daily activity" on public.user_daily_activity;
create policy "Users can view their own daily activity"
  on public.user_daily_activity
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create or replace function public.set_user_timezone(p_timezone text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_timezone text;
begin
  if v_user_id is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  select name into v_timezone
  from pg_timezone_names
  where name = nullif(trim(p_timezone), '');

  if v_timezone is null then
    v_timezone := 'UTC';
  end if;

  update public.profiles
  set timezone = v_timezone,
      updated_at = now()
  where id = v_user_id;

  return v_timezone;
end;
$$;

revoke all on function public.set_user_timezone(text) from public;
grant execute on function public.set_user_timezone(text) to authenticated;

create or replace function public.refresh_user_streak()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_question_id text := trim(p_question_id);
  v_timezone text;
  v_activity_date date;
  v_previous_date date;
  v_run integer := 0;
  v_current_streak integer := 0;
  v_longest_streak integer := 0;
  v_profile public.profiles%rowtype;
  v_row record;
begin
  if v_user_id is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  select coalesce(nullif(timezone, ''), 'UTC') into v_timezone
  from public.profiles
  where id = v_user_id;

  if v_timezone is null then
    raise exception 'profile_not_found' using errcode = 'P0002';
  end if;

  v_activity_date := (now() at time zone v_timezone)::date;

  for v_row in
    select activity_date
    from public.user_daily_activity
    where user_id = v_user_id
      and streak_day_completed
    order by activity_date
  loop
    if v_previous_date is null or v_row.activity_date = v_previous_date + 1 then
      v_run := v_run + 1;
    else
      v_run := 1;
    end if;

    v_longest_streak := greatest(v_longest_streak, v_run);
    if v_row.activity_date = v_activity_date then
      v_current_streak := v_run;
    end if;
    v_previous_date := v_row.activity_date;
  end loop;

  update public.profiles
  set current_streak = v_current_streak,
      longest_streak = v_longest_streak,
      updated_at = now()
  where id = v_user_id
  returning * into v_profile;

  return jsonb_build_object(
    'current_streak', v_profile.current_streak,
    'longest_streak', v_profile.longest_streak
  );
end;
$$;

revoke all on function public.refresh_user_streak() from public;
grant execute on function public.refresh_user_streak() to authenticated;

create or replace function public.record_question_completion(
  p_question_id text,
  p_is_correct boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_timezone text;
  v_activity_date date;
  v_activity public.user_daily_activity%rowtype;
  v_profile public.profiles%rowtype;
  v_was_new_completion boolean := false;
begin
  if v_user_id is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  if nullif(v_question_id, '') is null then
    raise exception 'question_id_required' using errcode = '22023';
  end if;

  select * into v_profile
  from public.profiles
  where id = v_user_id;

  if not found then
    raise exception 'profile_not_found' using errcode = 'P0002';
  end if;

  v_timezone := coalesce(nullif(v_profile.timezone, ''), 'UTC');
  v_activity_date := (now() at time zone v_timezone)::date;

  insert into public.user_daily_activity (user_id, activity_date)
  values (v_user_id, v_activity_date)
  on conflict (user_id, activity_date) do nothing;

  select * into v_activity
  from public.user_daily_activity
  where user_id = v_user_id
    and activity_date = v_activity_date
  for update;

  if not (v_question_id = any(v_activity.completed_exercise_ids)) then
    v_was_new_completion := true;

    update public.user_daily_activity
    set exercises_completed = exercises_completed + 1,
        completed_exercise_ids = array_append(completed_exercise_ids, v_question_id),
        streak_day_completed = exercises_completed + 1 >= 3,
        updated_at = now()
    where id = v_activity.id
    returning * into v_activity;

    update public.profiles
    set questions_answered = questions_answered + 1,
        questions_correct = questions_correct + case when p_is_correct then 1 else 0 end,
        updated_at = now()
    where id = v_user_id;
  end if;

  perform public.refresh_user_streak();
  select * into v_profile from public.profiles where id = v_user_id;

  return jsonb_build_object(
    'activity_date', v_activity_date,
    'exercises_completed', v_activity.exercises_completed,
    'streak_day_completed', v_activity.streak_day_completed,
    'new_completion', v_was_new_completion,
    'current_streak', v_profile.current_streak,
    'longest_streak', v_profile.longest_streak,
    'questions_answered', v_profile.questions_answered,
    'questions_correct', v_profile.questions_correct
  );
end;
$$;

revoke all on function public.record_question_completion(text, boolean) from public;
grant execute on function public.record_question_completion(text, boolean) to authenticated;

create or replace function public.set_user_daily_activity_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function public.set_user_daily_activity_updated_at() from public;

drop trigger if exists user_daily_activity_set_updated_at on public.user_daily_activity;
create trigger user_daily_activity_set_updated_at
before update on public.user_daily_activity
for each row
execute function public.set_user_daily_activity_updated_at();

